export default {
    SET_SIDEBAR_STATE: 'SET_SIDEBAR_STATE',
    SET_LOADING_STATE: 'SET_LOADING_STATE',
    SET_SCREEN_MODEL: 'SET_SCREEN_MODEL',
    SET_ACCOUNT_TOKEN: 'SET_ACCOUNT_TOKEN',
    CLEAR_ACCOUNt_TOKEN: 'CLEAR_ACCOUNt_TOKEN'
}