export default {
    SET_SIDEBAR_STATE: 'SET_SIDEBAR_STATE',
    SET_LOADING_STATE: 'SET_LOADING_STATE',
    SET_SCREEN_MODEL: 'SET_SCREEN_MODEL',
    SET_ACCOUNT_TOKEN: 'SET_ACCOUNT_TOKEN',
    CLEAR_ACCOUNT_TOKEN: 'CLEAR_ACCOUNt_TOKEN',
    SET_LOGIN_STATE: 'SET_LOGIN_STATE',
    SET_USER_ID: 'SET_USER_ID',
    GET_USER_ID: 'GET_USER_ID',
    SET_LOGIN_OR_REGISTER_STATE: 'SET_LOGIN_OR_REGISTER_STATE',
    SET_ONLINE_NUMBERS: 'SET_ONLINE_NUMBERS'
}